### ISSUE TITLE
cpanfile: s/develop/test/

### ISSUE THREAD

**Issue by andk** [polettix/Mojolicious-Plugin-TemplatePerlish#1]
The cpanfile contains:

on develop => sub {
   requires 'Path::Tiny', '0.084';
};

That 'develop' should be replaced by 'test', because Path::Tiny is actually required in the test t/00-load.t.

I have not tested it, but here is a fail report due missing Path::Tiny: http://www.cpantesters.org/cpan/report/64907832-1c20-11e6-ab41-c893a58a4b8c

That should be prevented with the suggested change.

**Comment by polettix** [comment]
Thanks, I didn't see/remember it. Too bad this didn't show up in Travis-CI, but I guess that's fair. I pushed a new trial release with the update... let's see.

Thanks again for taking the time!
